@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueContactList
AddressBook *-left-> "1" UniqueEventList
AddressBook *-down-> "1" UniqueTagList

UniqueTagList *--> "*" Tag
UniqueContactList --> Contact
UniqueEventList --> Event

Contact --> "*" Tag
Event --> "*" Tag
@enduml
