@startuml
!include style.puml

actor User

create ":CalendarWindow" as CalendarWindow UI_COLOR
User --> CalendarWindow : CalendarWindow(filteredList)
activate CalendarWindow
deactivate CalendarWindow

create ":CalendarView" as CalendarView UI_COLOR
CalendarWindow --> CalendarView : new
activate CalendarView
deactivate CalendarView

CalendarWindow --> CalendarWindow : createTimeThread()
note right: parallel thread to\nupdate calendar\nevery 10 seconds



@enduml