@startuml
'https://plantuml.com/activity-diagram-beta

start
:User enters elist command in the command box;
:EListCommandParser parses the command;
if () then ([valid arguments])

  if () then ([prefix present])
    :set corresponding fields
           to be displayed;

  else ([no prefix present])
  :set all fields to display;
  endif

else ([invalid arguments])
:throw ParseException with invalid command
format message and command usage;
endif

:returns feedback to user;

stop

@enduml
