@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Contact <<Rectangle>> {
Class UniqueContactList
Class Contact
Class Email
Class Phone
Class TelegramHandle
}

Package Common <<Rectangle>> {
Class Address
Class Name
Class ZoomLink
}

Package Event <<Rectangle>> {
Class UniqueEventList
Class Event
Class EndDateTime
Class DateAndTime
Class Description
Class StartDateTime
}

Package Tag <<Rectangle>> {
Class Tag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueContactList
UniqueContactList --> "~* all" Contact
Contact *--> "1" Name
Contact *--> "0..1" Phone
Contact *--> "1" Email
Contact *--> "0..1" Address
Contact *--> "0..1" ZoomLink
Contact *--> "0..1" TelegramHandle
Contact *--> "*" Tag

StartDateTime .down.|> DateAndTime
EndDateTime .down.|> DateAndTime

AddressBook *--> "1" UniqueEventList
UniqueEventList --> "~* all" Event
Event *--> "1" Name
Event *--> "0..1" Address
Event *--> "0..1" ZoomLink
Event *--> "0..1" Description
Event *--> "1" StartDateTime
Event *--> "0..1" EndDateTime
Event *--> "*" Tag

Tag -down[hidden]- Common
Address -up[hidden]- Name
Address -up[hidden]- ZoomLink
ZoomLink -up[hidden]- Name

ModelManager -->"~* filtered" Contact
ModelManager -->"~* filtered" Event

@enduml
