@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Interface ReadOnlyAddressBook <<Interface>>
Interface ReadOnlyUserPrefs <<Interface>>
Interface Model <<Interface>>
Class AddressBook
Class ReadOnlyAddressBook
Class Model
Class ModelManager
Class UserPrefs
Class ReadOnlyUserPrefs

Package Contact <<Rectangle>> {
Class UniqueContactList
Class Contact
Class Email
Class Phone
Class TelegramHandle
}

Package Common <<Rectangle>> {
Class Address
Class Name
Class ZoomLink
}

Package Event <<Rectangle>> {
Class UniqueEventList
Class Event
Class EndDateTime
Class DateAndTime
Class Description
Class StartDateTime
}

Package Tag <<Rectangle>> {
Class Tag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueContactList
UniqueContactList --> "~* all" Contact
Contact *--> Name
Contact *--> Phone
Contact *--> Email
Contact *--> Address
Contact *--> ZoomLink
Contact *--> TelegramHandle
Contact *--> "*" Tag

StartDateTime .down.|> DateAndTime
EndDateTime .down.|> DateAndTime

AddressBook *--> "1" UniqueEventList
UniqueEventList --> "~* all" Event
Event *--> Name
Event *--> Address
Event *--> ZoomLink
Event *--> Description
Event *--> StartDateTime
Event *--> EndDateTime
Event *--> "*" Tag

Tag -up[hidden]- Common

ModelManager -->"~* filtered" Contact
ModelManager -->"~* filtered" Event
@enduml
