@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor UI_COLOR_T4
skinparam classBackgroundColor UI_COLOR
'skinparam linetype ortho

package UI <<Rectangle>>{
Interface Ui <<Interface>>
Class "{abstract}\nUiPart" as UiPart
Class UiManager
Class MainWindow
Class CalendarWindow
Class ContactListPanel
Class EventListPanel
Class ContactCard
Class EventCard
package OtherUiComponents <<Rectangle>> {
Class HiddenComponent #FFFFFF
}
}

package Model <<Rectangle>> {
Class Event
Class Contact
}

package Logic <<Rectangle>> {
Class HiddenLogic #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Ui

UiManager .left.|> Ui
UiManager -down-> "1" MainWindow
Ui -[hidden]---> OtherUiComponents
MainWindow *--> OtherUiComponents
MainWindow *--> "1" ContactListPanel
MainWindow *--> "1" EventListPanel
MainWindow *--> "0..1" CalendarWindow

ContactListPanel -down-> "*" ContactCard
EventListPanel -down-> "*" EventCard

MainWindow -left-|> UiPart

ContactListPanel --|> UiPart
EventListPanel --|> UiPart
ContactCard --|> UiPart
EventCard --|> UiPart
CalendarWindow --|> UiPart
OtherUiComponents --|> UiPart

ContactCard ..> Contact
EventCard ..> Event
CalendarWindow --> Event : calendar of >
UiManager -right-> Logic
MainWindow -left-> Logic

'MainWindow -[hidden]-|> UiPart
ContactListPanel -[hidden]left- EventListPanel
@enduml
